

language: R

sudo: required

group: deprecated-2017Q2

cache: packages

warnings_are_errors: false,

before_install: 
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:marutter/rrutter -y; fi
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get update                            ; fi
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install r-cran-rjags              ; fi

addons:
  apt: 
    sources: 
       - ubuntu-toolchain-r-test
    packages:
       - gcc-6
       - g++-6

dist: trusty

os:
  - linux
  - osx
