

language: R

sudo: required

group: deprecated-2017Q2

cache: packages

warnings_are_errors: false,

before_install: 
  - sudo add-apt-repository ppa:marutter/rrutter -y
  - sudo apt-get update
  - sudo apt-get install r-cran-rjags

addons:
  apt: 
    sources: 
       - ubuntu-toolchain-r-test
    packages:
       - gcc-6
       - g++-6

dist: trusty

os:
  - linux
  - osx
