#' Plot method for the imputed data contained in the objects of class \code{missingHE}
#'
#' Produces a plot of the observed and imputed values (with credible intervals) for the effect and cost outcomes from a
#' Bayesian cost-effectiveness analysis model with two treatment arms, implemented using the function \code{\link{selection}}, \code{\link{pattern}}, 
#' \code{\link{hurdle}} or \code{\link{lmdm}}.
#' The graphical layout is obtained from the functions contained in the package \strong{ggplot2} and \strong{ggthemes}.
#' @keywords plot missing data 
#' @param x A \code{missingHE} object containing the results of the Bayesian model for cost-effectiveness analysis.
#' @param prob A numeric vector of probabilities representing the upper and lower CI sample quantiles to be calculated and returned for the imputed values.
#' @param class Type of the plot comparing the observed and imputed outcome data. Available choices are
#' 'scatter' (default), 'histogram' and 'boxplot' for a scatter, histogram or a boxplot of the observed and average imputed outcome data, respectively.
#' @param outcome The outcome variables that should be displayed. Options are: 'both' (default) for both effects and costs; 'effects' or 'costs' for the effects
#' or costs separately.
#' @param trt treatment group for which plots should be displayed. Choices include: 'all' (default) for all groups; 'none' for results across all groups; any 
#' character or numeric value denoting the treatment group name or index associated with the treatment variable in the original data set.
#' @param time_plot Time point for which the graphs should be displayed.
#' @param theme Type of ggplot theme among some pre-defined themes, mostly taken from the package \strong{ggthemes}. For a full list of available themes see details.
#' @param only.plot Logical. If \code{only.plot} is \code{TRUE} (default) only the plot is returned. When \code{only.plot} is \code{FALSE}, a list containing the plot object and the data is returned instead. 
#' @param ... Additional parameters that can be provided to manage the output of \code{plot.missingHE}. 
#' @return A \code{ggplot} object containing the plots specified in the argument \code{class}.
#' @seealso \code{\link{selection}} \code{\link{pattern}} \code{\link{hurdle}} \code{\link{lmdm}} \code{\link{diagnostic}}
#' @details The function produces a plot of the observed and imputed effect and cost data in a two-arm based 
#' cost-effectiveness model implemented using the function \code{\link{selection}}, \code{\link{pattern}}, \code{\link{hurdle}} or or \code{\link{lmdm}}. 
#' The purpose of this graph is to visually compare the outcome values for the fully-observed individuals with those imputed by the model for the missing individuals.
#' For scatter plots, average imputed values are also associated with credible intervals specified in the argument \code{prob}.
#' The argument \code{theme} allows to customise the graphical aspect of the plots generated by \code{plot.missingHE} and
#' allows to choose among a set of possible pre-defined themes taken form the package \strong{ggtheme}. For a complete list of the available character names
#' for each theme and scheme set, see \strong{ggthemes} and \strong{bayesplot}.
#' @author Andrea Gabrio
#' @references 
#' Daniels, MJ. Hogan, JW. (2008) \emph{Missing Data in Longitudinal Studies: strategies for Bayesian modelling and sensitivity analysis}, CRC/Chapman Hall.
#'
#' Molenberghs, G. Fitzmaurice, G. Kenward, MG. Tsiatis, A. Verbeke, G. (2015) \emph{Handbook of Missing Data Methodology}, CRC/Chapman Hall.
#' @import ggplot2 
#' @export 
#' @examples
#' # For examples see the function \code{\link{selection}}, \code{\link{pattern}},
#' # \code{\link{hurdle}} or \code{\link{lmdm}}
#' #
#' #

plot.missingHE <- function(x, prob = c(0.025, 0.975), 
                           class = "scatter", outcome = "both", trt = "all", 
                           time_plot = NULL, theme = NULL, only.plot = TRUE, ...) {
  if(!isTRUE(requireNamespace("ggplot2")) | !isTRUE(requireNamespace("ggthemes"))) {
    stop("You need to install the R package 'ggplot2'. 
         Please run in your R terminal:\n install.packages('ggplot2')")}
  if(is.null(theme)) { theme = "classic"}
  if(!theme %in% c("classic", "base", "calc", "economist", "excel", "few", "538", "gdocs", 
                   "hc", "par", "pander", "solarized", "stata", "tufte", "wsj")) {
    stop("Please provide a valid theme type among those available. Type ''help(ggthemes)'' for more details.")}
  if(!is.logical(only.plot)) { stop("Please provide a logical value to the 'only.plot' argument.")}
  if(!class %in% c("scatter", "histogram", "boxplot")) {
    stop("Please provide a plot class name among those available.")}
  if(!outcome %in% c("both", "effects", "costs")) {
    stop("Please provide an outcome name among those available.")}
  n_trt <- length(x$data_set$data_raw$trt_index)
  trt_lev <- names(x$data_set$data_raw$trt_index)
  if(!inherits(x, "missingHE")) {
    stop("Only objects of class 'missingHE' can be used")}
  if(!is.vector(prob) | length(prob) != 2 | !is.numeric(prob) | any(prob <= 0 | prob >= 1)) {
    stop("Please provide a lower and an upper quantile for the imputed data distribution")}  
  exArgs <- list(...)
  if(exists("size", where = exArgs)) { plot.size = exArgs$size } else { plot.size = 0.25}
  if(exists("color", where = exArgs)) { plot.color = exArgs$color } else { plot.color = c("black", "red")}
  if(exists("shape", where = exArgs)) { plot.shape = exArgs$shape } else { plot.shape = c(16, 16)}
  if(exists("linetype", where = exArgs)) { plot.linetype = exArgs$linetype } else { plot.linetype = c(0, 1)}
  if(exists("dodge", where = exArgs)) { plot.dodge = exArgs$dodge } else { plot.dodge = 0.1}
  if(exists("fill", where = exArgs)) { plot.fill = exArgs$fill } else { plot.fill = "white"}
  if(exists("legend.position", where = exArgs)) { legend.pos = exArgs$legend.position } else { legend.pos = "top"}
  if(exists("bins", where = exArgs)) { bins = exArgs$bins } else { bins = 30}
  Individuals <- Mean <- QL <- QU <- Type <- e <- NULL
  if(is.numeric(trt)) {
    if(length(trt) == 1 & !any(trt %in% c(1:n_trt))) {
      stop("Please provide a trt value among those available.")
    } else if(length(trt) > 1 & !any(trt %in% c(2:n_trt))){
      stop("Please provide a trt value among those available.")}
  } else if(is.character(trt)) {
    if(length(trt) == 1 & !any(trt %in% c("all", trt_lev, "none"))) {
      stop("Please provide a trt name among those available.")
    } else if(length(trt) > 1 & !length(trt) %in% c(2:n_trt)){
      stop("Please provide a trt name among those available.")}
  } else { stop("Please provide a trt name or value among those available.")}
  if(any(x$data_set$data_raw$n_mis_e == 0) & outcome %in% c("effects", "both")) {
    stop("No missing values found in the data to be plotted")}
  if(any(x$data_set$data_raw$n_mis_c == 0) & outcome %in% c("costs", "both")) {
    stop("No missing values found in the data to be plotted")}
  if(x$data_format == "wide") {
    n_all <- sum(x$data_set$data_raw$n)
    meff_all <- mcost_all <- matrix(NA, nrow = n_all, ncol = 3)
    colnames(meff_all) <- colnames(mcost_all) <- c("Mean", "QL", "QU")
    meff_all[, "Mean"] <- apply(x$model_output$model$BUGSoutput$sims.list$eff, 2, mean, na.rm = TRUE)
    meff_all[, "QL"] <- apply(x$model_output$model$BUGSoutput$sims.list$eff, 2, quantile, probs = prob[1], na.rm = TRUE)
    meff_all[, "QU"] <- apply(x$model_output$model$BUGSoutput$sims.list$eff, 2, quantile, probs = prob[2], na.rm = TRUE)
    mcost_all[, "Mean"] <- apply(x$model_output$model$BUGSoutput$sims.list$cost, 2, mean, na.rm = TRUE)
    mcost_all[, "QL"] <- apply(x$model_output$model$BUGSoutput$sims.list$cost, 2, quantile, probs = prob[1], na.rm = TRUE)
    mcost_all[, "QU"] <- apply(x$model_output$model$BUGSoutput$sims.list$cost, 2, quantile, probs = prob[2], na.rm = TRUE)
    lefft_all <- lcostt_all <- list()
    lefft_obs <- lcostt_obs <- list()
    lefft_mis <- lcostt_mis <- list()
    trt_index <- x$data_set$data_raw$trt_index
    for(i in trt_lev) { 
      lefft_all[[i]] <- as.data.frame(meff_all[trt_index[[i]], ])
      lcostt_all[[i]] <- as.data.frame(mcost_all[trt_index[[i]], ])
      lefft_obs[[i]] <- lefft_all[[i]][x$data_set$data_raw$m_efft[[i]] == 0, ]
      lcostt_obs[[i]] <- lcostt_all[[i]][x$data_set$data_raw$m_costt[[i]] == 0, ]
      lefft_mis[[i]] <- lefft_all[[i]][x$data_set$data_raw$m_efft[[i]] == 1, ]
      lcostt_mis[[i]] <- lcostt_all[[i]][x$data_set$data_raw$m_costt[[i]] == 1, ]
    }
    me_type <- ifelse(x$data_set$data_raw$me == 1, "missing", "observed")
    mc_type <- ifelse(x$data_set$data_raw$mc == 1, "missing", "observed")
    list.data <- list("complete" = list("effects" = lefft_all, "costs" = lcostt_all),
                      "observed" = list("effects" = lefft_obs, "costs" = lcostt_obs),
                      "imputed" = list("effects" = lefft_mis, "costs" = lcostt_mis))
    if(class == "scatter"){
      meff_all[me_type == "observed", c("QL", "QU")] <- NA
      mcost_all[mc_type == "observed", c("QL", "QU")] <- NA}
    df.all <- data.frame(Individuals = rep(seq(1:n_all), 2), 
                         Var = factor(c(rep("effects", n_all), rep("costs", n_all)), levels = c("effects", "costs")),
                         Mean = c(meff_all[, "Mean"], mcost_all[, "Mean"]), 
                         QL = c(meff_all[, "QL"], mcost_all[, "QL"]), 
                         QU = c(meff_all[, "QU"], mcost_all[, "QU"]), 
                         Type = factor(c(me_type, mc_type), levels = c("observed", "missing")),
                         trt = c(x$data_set$data_raw$data$trt, x$data_set$data_raw$data$trt))
    if(outcome == "both") { df.plot <- df.all}
    if(outcome == "effects") { df.plot <- df.all[df.all$Var == "effects", ]}
    if(outcome == "costs") { df.plot <- df.all[df.all$Var == "costs", ]}
    if(length(trt) == 1) {
      if(trt == "none") { 
        df.plot <- df.plot[, -which(names(df.plot) == "trt")]
        df.trt_name <- "none"}
      if(trt == "all") {
        df.plot <- df.plot
        df.trt_name <- trt <- trt_lev}
      if(!any(trt %in% c("all", "none")) & is.character(trt)) { 
        df.plot <- df.plot[df.plot$trt %in% trt, ]
        df.trt_name <- trt
        df.plot$trt <- factor(df.plot$trt, levels = df.trt_name)}
    } 
    if(length(trt) > 1 & is.character(trt)) { 
        df.plot <- df.plot[df.plot$trt %in% trt, ]
        df.trt_name <- trt
        df.plot$trt <- factor(df.plot$trt, levels = df.trt_name)}
    if(is.numeric(trt)) { 
      df.trt_name <- trt_lev[trt]
      df.plot <- df.plot[df.plot$trt %in% df.trt_name, ]
      df.plot$trt <- factor(df.plot$trt, levels = df.trt_name)}
  }
  if(x$data_format == "long") {
    max_time <- max(as.numeric(x$data_set$data_raw$time_long), na.rm = TRUE)
    if(exists("time.plot", where = exArgs)) { time.plot = exArgs$time.plot } else { time.plot = 1}
    if(is.numeric(time.plot)) {
      if(length(time.plot) == 1 & !any(time.plot %in% c(1:max_time))) {
        stop("Please provide a time.plot value among those available.")
      } else if(length(time.plot) > 1 & !any(time.plot %in% c(2:max_time))){
        stop("Please provide a time.plot value among those available.")}
    } else if(is.character(time.plot)) {
      if(length(time.plot) == 1 & !any(time.plot %in% c("all", 1:max_time))) {
        stop("Please provide a time.plot name among those available.")
      } else if(length(time.plot) > 1 & !length(time.plot) %in% c(2:max_time)){
        stop("Please provide a time.plot name among those available.")}
    } else { stop("Please provide a time.plot name or value among those available.")}
    if(any(x$data_set$data_raw$n_mis_e == 0) & outcome %in% c("effects", "both")) {
      stop("No missing values found in the data to be plotted")}
    if(any(x$data_set$data_raw$n_mis_c == 0) & outcome %in% c("costs", "both")) {
      stop("No missing values found in the data to be plotted")}
    if(length(time.plot) == 1) {
      if(time.plot == "all") { time.plot <- 1:max_time}
    }
    time.plot.num <- as.numeric(time.plot)
    if(any(x$data_set$data_raw$n_mis_time_e[time.plot.num] == 0) & outcome %in% c("effects", "both")) {
      stop("No missing values found in the data to be plotted")}
    if(any(x$data_set$data_raw$n_mis_time_c[time.plot.num] == 0) & outcome %in% c("costs", "both")) {
      stop("No missing values found in the data to be plotted")}
    n_all <- sum(x$data_set$data_raw$n_long)
    meff_all <- mcost_all <- matrix(NA, nrow = n_all, ncol = 3)
    colnames(meff_all) <- colnames(mcost_all) <- c("Mean", "QL", "QU")
    meff_all[, "Mean"] <- apply(as.matrix(as.data.frame(x$model_output$model$BUGSoutput$sims.list$eff)), 2, mean, na.rm = TRUE)
    meff_all[, "QL"] <- apply(as.matrix(as.data.frame(x$model_output$model$BUGSoutput$sims.list$eff)), 2, quantile, probs = prob[1], na.rm = TRUE)
    meff_all[, "QU"] <- apply(as.matrix(as.data.frame(x$model_output$model$BUGSoutput$sims.list$eff)), 2, quantile, probs = prob[2], na.rm = TRUE)
    mcost_all[, "Mean"] <- apply(as.matrix(as.data.frame(x$model_output$model$BUGSoutput$sims.list$cost)), 2, mean, na.rm = TRUE)
    mcost_all[, "QL"] <- apply(as.matrix(as.data.frame(x$model_output$model$BUGSoutput$sims.list$cost)), 2, quantile, probs = prob[1], na.rm = TRUE)
    mcost_all[, "QU"] <- apply(as.matrix(as.data.frame(x$model_output$model$BUGSoutput$sims.list$cost)), 2, quantile, probs = prob[2], na.rm = TRUE)
    lefft_all <- lcostt_all <- list()
    lefft_obs <- lcostt_obs <- list()
    lefft_mis <- lcostt_mis <- list()
    trt_index <- x$data_set$data_raw$trt_index_long
    for(i in trt_lev) { 
      lefft_all[[i]] <- as.data.frame(meff_all[trt_index[[i]], ])
      lcostt_all[[i]] <- as.data.frame(mcost_all[trt_index[[i]], ])
      lefft_obs[[i]] <- lefft_all[[i]][x$data_set$data_raw$m_efft[[i]] == 0, ]
      lcostt_obs[[i]] <- lcostt_all[[i]][x$data_set$data_raw$m_costt[[i]] == 0, ]
      lefft_mis[[i]] <- lefft_all[[i]][x$data_set$data_raw$m_efft[[i]] == 1, ]
      lcostt_mis[[i]] <- lcostt_all[[i]][x$data_set$data_raw$m_costt[[i]] == 1, ]
    }
    ltimet <- x$data_set$data_raw$timet
    me_type <- ifelse(x$data_set$data_raw$me == 1, "missing", "observed")
    mc_type <- ifelse(x$data_set$data_raw$mc == 1, "missing", "observed")
    list.data <- list("complete" = list("effects" = lefft_all, "costs" = lcostt_all),
                      "observed" = list("effects" = lefft_obs, "costs" = lcostt_obs),
                      "imputed" = list("effects" = lefft_mis, "costs" = lcostt_mis),
                      "time" = ltimet)
    if(class == "scatter"){
      meff_all[me_type == "observed", c("QL", "QU")] <- NA
      mcost_all[mc_type == "observed", c("QL", "QU")] <- NA}
    df.all <- data.frame(Individuals = rep(seq(1:n_all), 2), 
                         Var = factor(c(rep("effects", n_all), rep("costs", n_all)), levels = c("effects", "costs")),
                         Mean = c(meff_all[, "Mean"], mcost_all[, "Mean"]), 
                         QL = c(meff_all[, "QL"], mcost_all[, "QL"]), 
                         QU = c(meff_all[, "QU"], mcost_all[, "QU"]), 
                         Type = factor(c(me_type, mc_type), levels = c("observed", "missing")),
                         trt = c(x$data_set$data_raw$data$trt, x$data_set$data_raw$data$trt),
                         time = factor(c(x$data_set$data_raw$time_long, x$data_set$data_raw$time_long), levels = 1:max_time))
    if(outcome == "both") { df.plot <- df.all}
    if(outcome == "effects") { df.plot <- df.all[df.all$Var == "effects", ]}
    if(outcome == "costs") { df.plot <- df.all[df.all$Var == "costs", ]}
    if(length(time.plot) == 1) {
      if(time.plot == "all") { 
        df.plot <- df.plot
        df.time_name <- 1:max_time}
      if(!time.plot %in% c("all") & is.character(time.plot)) { 
        df.plot <- df.plot[df.plot$time %in% time.plot, ]
        df.time_name <- time.plot
        df.plot$time <- factor(df.plot$time, levels = df.time_name)}
    }
    if(length(time.plot) > 1 & is.character(time.plot)) { 
      df.plot <- df.plot[df.plot$time %in% time.plot, ]
      df.time_name <- time.plot
      df.plot$time <- factor(df.plot$time, levels = df.time_name)}
    if(is.numeric(time.plot)) { 
      df.time_name <- c(1:max_time)[time.plot]
      df.plot <- df.plot[df.plot$time %in% df.time_name, ]
      df.plot$time <- factor(df.plot$time, levels = df.time_name)}
    if(length(trt) == 1) {
      if(trt == "none") { 
        df.plot <- df.plot[, -which(names(df.plot) == "trt")]
        df.trt_name <- "none"}
      if(trt == "all") { 
        df.plot <- df.plot
        df.trt_name <- trt_lev}
      if(!trt %in% c("all", "none") & is.character(trt)) { 
        df.plot <- df.plot[df.plot$trt %in% trt, ]
        df.trt_name <- trt
        df.plot$trt <- factor(df.plot$trt, levels = df.trt_name)}
    } 
    if(length(trt) > 1 & is.character(trt)) { 
      df.plot <- df.plot[df.plot$trt %in% trt, ]
      df.trt_name <- trt
      df.plot$trt <- factor(df.plot$trt, levels = df.trt_name)}
    if(is.numeric(trt)) { 
      df.trt_name <- trt_lev[trt]
      df.plot <- df.plot[df.plot$trt %in% df.trt_name, ]
      df.plot$trt <- factor(df.plot$trt, levels = df.trt_name)}
  }
    if(class == "scatter") {
      pd <- ggplot2::position_dodge(plot.dodge)
      gplot <- ggplot2::ggplot(df.plot, ggplot2::aes(colour = Type, x = Individuals, y = Mean)) +
        ggplot2::geom_point(position = pd, na.rm = TRUE) +
        ggplot2::geom_pointrange(data = df.plot, mapping = ggplot2::aes(x = Individuals, y = Mean, ymin = QL, ymax = QU), 
                                 size = plot.size, na.rm = TRUE) + 
        ggplot2::scale_colour_manual(values = plot.color, 
                                     guide = ggplot2::guide_legend(override.aes = list(shape = plot.shape, linetype = plot.linetype))) 
    }
    if(class == "histogram") {
      if(exists("hist.use", where = exArgs)) { 
        hist.use = exArgs$hist.use 
        if(hist.use == "QL") {
          gplot <- ggplot2::ggplot(df.plot, ggplot2::aes(x = QL, color = Type)) + 
            ggplot2::geom_histogram(fill = plot.fill, position = "dodge", bins = bins) + 
            ggplot2::scale_colour_manual(values = plot.color)
        }
        if(hist.use == "QU") {
          gplot <- ggplot2::ggplot(df.plot, ggplot2::aes(x = QU, color = Type)) + 
            ggplot2::geom_histogram(fill = plot.fill, position = "dodge", bins = bins) + 
            ggplot2::scale_colour_manual(values = plot.color)
        } else {
          gplot <- ggplot2::ggplot(df.plot, ggplot2::aes(x = Mean, color = Type)) + 
            ggplot2::geom_histogram(fill = plot.fill, position = "dodge", bins = bins) + 
            ggplot2::scale_colour_manual(values = plot.color)
        }
      } else { 
        gplot <- ggplot2::ggplot(df.plot, ggplot2::aes(x = Mean, color = Type)) + 
          ggplot2::geom_histogram(fill = plot.fill, position = "dodge", bins = bins) + 
          ggplot2::scale_colour_manual(values = plot.color) 
      }
    }
    if(class == "boxplot") {
      if(exists("box.use", where = exArgs)) { 
        box.use = exArgs$box.use 
        if(box.use == "QL") {
          gplot <- ggplot2::ggplot(df.plot, ggplot2::aes(x = QL, color = Type)) + 
            ggplot2::geom_boxplot(fill = plot.fill, position = "dodge2") + 
            ggplot2::scale_colour_manual(values = plot.color)
        }
        if(box.use == "QU") {
          gplot <- ggplot2::ggplot(df.plot, ggplot2::aes(x = QU, color = Type)) + 
            ggplot2::geom_boxplot(fill = plot.fill, position = "dodge2") + 
            ggplot2::scale_colour_manual(values = plot.color)
        } else {
          gplot <- ggplot2::ggplot(df.plot, ggplot2::aes(x = Mean, color = Type)) + 
            ggplot2::geom_boxplot(fill = plot.fill, position = "dodge2") + 
            ggplot2::scale_colour_manual(values = plot.color)
        }
      } else { 
        gplot <- ggplot2::ggplot(df.plot, ggplot2::aes(x = Mean, color = Type)) + 
          ggplot2::geom_boxplot(fill = plot.fill, position = "dodge2") + 
          ggplot2::scale_colour_manual(values = plot.color)
      }
    }
  if(x$data_format == "wide") {
    if(length(df.trt_name) == 1) {
    if(df.trt_name == "none"){
      gplot <- gplot + ggplot2::facet_wrap( ~ Var, scales = "free")}
    if(df.trt_name %in% trt_lev){
      gplot <- gplot + ggplot2::facet_wrap( ~ Var, scales = "free")}
    }
    if(length(df.trt_name) > 1) {
      if(all(df.trt_name %in% trt_lev)){
        gplot <- gplot + ggplot2::facet_wrap(Var ~ trt, scales = "free")
      }
      if(!any(df.trt_name %in% trt_lev)){
        stop("Please provide only valid treatment names or values.")
      }
    }
  }
  if(x$data_format == "long") {
    if(length(df.trt_name) == 1 & length(df.time_name) == 1) {
      if(df.time_name %in% as.character(1:max_time)){
      if(df.trt_name == "none"){
        gplot <- gplot + ggplot2::facet_wrap( ~ Var, scales = "free")}
      if(df.trt_name %in% trt_lev){
        gplot <- gplot + ggplot2::facet_wrap( ~ Var, scales = "free")}
      }
    }
    if(length(df.trt_name) == 1 & length(df.time_name) > 1) {
      if(all(df.time_name %in% as.character(1:max_time))){
        if(df.trt_name == "none"){
          gplot <- gplot + ggplot2::facet_wrap( ~ Var + time, scales = "free")}
        if(df.trt_name %in% trt_lev){
          gplot <- gplot + ggplot2::facet_wrap( ~ Var + time, scales = "free")}
      }
      if(!any(df.time_name %in% as.character(1:max_time))){
        stop("Please provide only valid time values.")
      }
    }
    if(length(df.trt_name) > 1 & length(df.time_name) == 1) {
      if(df.time_name %in% as.character(1:max_time)){
      if(all(df.trt_name %in% trt_lev)){
        gplot <- gplot + ggplot2::facet_wrap(Var ~ trt, scales = "free")
      }
      if(!any(df.trt_name %in% trt_lev)){
        stop("Please provide only valid treatment names or values.")
      }
      }
    }
    if(length(df.trt_name) > 1 & length(df.time_name) > 1) {
      if(all(df.time_name %in% as.character(1:max_time))){
        if(all(df.trt_name %in% trt_lev)){
          gplot <- gplot + ggplot2::facet_wrap(Var ~ trt + time, scales = "free")
        }
        if(!any(df.trt_name %in% trt_lev)){
          stop("Please provide only valid treatment names or values.")
        }
      }
      if(!any(df.time_name %in% as.character(1:max_time))){
        stop("Please provide only valid time values.")
      }
    }
  }
  gplot <- gplot + ggplot2::theme(legend.position = legend.pos)
    if(theme == "classic") {
      gplot <- gplot + ggplot2::theme(panel.grid.major = ggplot2::element_blank(), 
                               panel.grid.minor = ggplot2::element_blank(), 
                               panel.background = ggplot2::element_blank(), 
                               axis.line = ggplot2::element_line(colour = "black"), 
                               strip.background = ggplot2::element_rect(fill="white"), 
                               strip.text.x = ggplot2::element_text(size = 12, color = "black", face = "bold"),
                               strip.text.y = ggplot2::element_text(size = 12, color = "black", face = "bold"))
    }
    if(theme == "base") { gplot <- gplot + ggthemes::theme_base() + ggplot2::theme(legend.position = legend.pos)} 
    if(theme == "calc") { gplot <- gplot + ggthemes::theme_calc() + ggplot2::theme(legend.position = legend.pos)} 
    if(theme == "economist") { gplot <- gplot + ggthemes::theme_economist() + ggplot2::theme(legend.position = legend.pos)} 
    if(theme == "excel") { gplot <- gplot + ggthemes::theme_excel() + ggplot2::theme(legend.position = legend.pos)} 
    if(theme == "few") { gplot <- gplot + ggthemes::theme_few() + ggplot2::theme(legend.position = legend.pos)} 
    if(theme == "538") { gplot <- gplot + ggthemes::theme_fivethirtyeight() + ggplot2::theme(legend.position = legend.pos)} 
    if(theme == "gdocs") { gplot <- gplot + ggthemes::theme_gdocs() + ggplot2::theme(legend.position = legend.pos)} 
    if(theme == "hc") { gplot <- gplot + ggthemes::theme_hc() + ggplot2::theme(legend.position = legend.pos)} 
    if(theme == "par") { gplot <- gplot + ggthemes::theme_par() + ggplot2::theme(legend.position = legend.pos)} 
    if(theme == "solarized") { gplot <- gplot + ggthemes::theme_solarized() + ggplot2::theme(legend.position = legend.pos)} 
    if(theme == "pander") { gplot <- gplot + ggthemes::theme_pander() + ggplot2::theme(legend.position = legend.pos)} 
    if(theme == "stata") { gplot <- gplot + ggthemes::theme_stata() + ggplot2::theme(legend.position = legend.pos)} 
    if(theme == "tufte") { gplot <- gplot + ggthemes::theme_tufte() + ggplot2::theme(legend.position = legend.pos)} 
    if(theme == "wsj") { gplot <- gplot + ggthemes::theme_wsj() + ggplot2::theme(legend.position = legend.pos)} 
    res_plot <- list("plot" = gplot, "list.data" = list.data)
    if(only.plot) { return(res_plot$plot)}
    if(!only.plot) { return(invisible(res_plot))}
}